version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node
        environment:
          AGENDA_MAIL_DATABASE_PASSWORD: qwe123
          RAILS_ENV: test
      - image: postgres:12
        environment:
          POSTGRES_USER: agenda_mail
          POSTGRES_DB: agenda_mail_test
          POSTGRES_PASSWORD: qwe123
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: your-app-name-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: your-app-name-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # - run: gem install bundler
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle install
      - run: bundle exec rails db:setup
